export type MenuAction =
  | 'open-folder'
  | 'save'
  | 'close-tab'
  | 'reopen-tab'
  | 'go-to-file'
  | 'find-in-files'
  | 'toggle-git-panel'
  | 'toggle-dictation'
  | 'format-document'
  | 'toggle-preview'
  | 'toggle-terminal'
  | 'preferences'
